// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ua.com.blogengine.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import ua.com.blogengine.domain.Article;
import ua.com.blogengine.domain.ArticleDataOnDemand;
import ua.com.blogengine.domain.SectionDataOnDemand;

privileged aspect ArticleDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ArticleDataOnDemand: @Component;
    
    private Random ArticleDataOnDemand.rnd = new SecureRandom();
    
    private List<Article> ArticleDataOnDemand.data;
    
    @Autowired
    private SectionDataOnDemand ArticleDataOnDemand.sectionDataOnDemand;
    
    public Article ArticleDataOnDemand.getNewTransientArticle(int index) {
        Article obj = new Article();
        setContent(obj, index);
        setHtmlContent(obj, index);
        setHtmlPreamble(obj, index);
        setPublicationDate(obj, index);
        setPublished(obj, index);
        setSubmissionDate(obj, index);
        setTitle(obj, index);
        setUrlTitle(obj, index);
        return obj;
    }
    
    public void ArticleDataOnDemand.setContent(Article obj, int index) {
        String content = "content_" + index;
        obj.setContent(content);
    }
    
    public void ArticleDataOnDemand.setHtmlContent(Article obj, int index) {
        String htmlContent = "htmlContent_" + index;
        obj.setHtmlContent(htmlContent);
    }
    
    public void ArticleDataOnDemand.setHtmlPreamble(Article obj, int index) {
        String htmlPreamble = "htmlPreamble_" + index;
        obj.setHtmlPreamble(htmlPreamble);
    }
    
    public void ArticleDataOnDemand.setPublicationDate(Article obj, int index) {
        Date publicationDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setPublicationDate(publicationDate);
    }
    
    public void ArticleDataOnDemand.setPublished(Article obj, int index) {
        Boolean published = true;
        obj.setPublished(published);
    }
    
    public void ArticleDataOnDemand.setSubmissionDate(Article obj, int index) {
        Date submissionDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setSubmissionDate(submissionDate);
    }
    
    public void ArticleDataOnDemand.setTitle(Article obj, int index) {
        String title = "title_" + index;
        obj.setTitle(title);
    }
    
    public void ArticleDataOnDemand.setUrlTitle(Article obj, int index) {
        String urlTitle = "urlTitle_" + index;
        obj.setUrlTitle(urlTitle);
    }
    
    public Article ArticleDataOnDemand.getSpecificArticle(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Article obj = data.get(index);
        Long id = obj.getId();
        return Article.findArticle(id);
    }
    
    public Article ArticleDataOnDemand.getRandomArticle() {
        init();
        Article obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Article.findArticle(id);
    }
    
    public boolean ArticleDataOnDemand.modifyArticle(Article obj) {
        return false;
    }
    
    public void ArticleDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Article.findArticleEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Article' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Article>();
        for (int i = 0; i < 10; i++) {
            Article obj = getNewTransientArticle(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
