// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ua.com.blogengine.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ua.com.blogengine.domain.ArticleDataOnDemand;

privileged aspect ArticleDataOnDemand_Roo_Configurable {
    
    declare @type: ArticleDataOnDemand: @Configurable;
    
}
