// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ua.com.blogengine.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import ua.com.blogengine.domain.Section;
import ua.com.blogengine.domain.SectionDataOnDemand;

privileged aspect SectionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SectionDataOnDemand: @Component;
    
    private Random SectionDataOnDemand.rnd = new SecureRandom();
    
    private List<Section> SectionDataOnDemand.data;
    
    public Section SectionDataOnDemand.getNewTransientSection(int index) {
        Section obj = new Section();
        setName(obj, index);
        setUrlName(obj, index);
        return obj;
    }
    
    public void SectionDataOnDemand.setName(Section obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void SectionDataOnDemand.setUrlName(Section obj, int index) {
        String urlName = "urlName_" + index;
        obj.setUrlName(urlName);
    }
    
    public Section SectionDataOnDemand.getSpecificSection(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Section obj = data.get(index);
        Long id = obj.getId();
        return Section.findSection(id);
    }
    
    public Section SectionDataOnDemand.getRandomSection() {
        init();
        Section obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Section.findSection(id);
    }
    
    public boolean SectionDataOnDemand.modifySection(Section obj) {
        return false;
    }
    
    public void SectionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Section.findSectionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Section' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Section>();
        for (int i = 0; i < 10; i++) {
            Section obj = getNewTransientSection(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
