// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ua.com.blogengine.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ua.com.blogengine.domain.Section;
import ua.com.blogengine.domain.SectionDataOnDemand;
import ua.com.blogengine.domain.SectionIntegrationTest;

privileged aspect SectionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SectionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SectionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SectionIntegrationTest: @Transactional;
    
    @Autowired
    private SectionDataOnDemand SectionIntegrationTest.dod;
    
    @Test
    public void SectionIntegrationTest.testCountSections() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        Assert.assertTrue("Counter for 'Section' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SectionIntegrationTest.testFindSection() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        Assert.assertNotNull("Find method for 'Section' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Section' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SectionIntegrationTest.testFindAllSections() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        Assert.assertTrue("Too expensive to perform a find all test for 'Section', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Section> result = Section.findAllSections();
        Assert.assertNotNull("Find all method for 'Section' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Section' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SectionIntegrationTest.testFindSectionEntries() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        long count = Section.countSections();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Section> result = Section.findSectionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Section' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Section' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SectionIntegrationTest.testFlush() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        Assert.assertNotNull("Find method for 'Section' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySection(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Section' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SectionIntegrationTest.testMergeUpdate() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        boolean modified =  dod.modifySection(obj);
        Integer currentVersion = obj.getVersion();
        Section merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Section' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SectionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", dod.getRandomSection());
        Section obj = dod.getNewTransientSection(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Section' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Section' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Section' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SectionIntegrationTest.testRemove() {
        Section obj = dod.getRandomSection();
        Assert.assertNotNull("Data on demand for 'Section' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Section' failed to provide an identifier", id);
        obj = Section.findSection(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Section' with identifier '" + id + "'", Section.findSection(id));
    }
    
}
